# Generated by Django 4.2.3 on 2023-10-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_macbooks_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipads',
            old_name='description',
            new_name='keyfeature',
        ),
        migrations.RenameField(
            model_name='macbooks',
            old_name='description',
            new_name='keyfeature',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='description',
            new_name='keyfeature',
        ),
        migrations.RemoveField(
            model_name='ipads',
            name='category',
        ),
        migrations.RemoveField(
            model_name='macbooks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='category',
        ),
    ]
