# Generated by Django 4.2.3 on 2023-10-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_description_ipads_keyfeature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipads',
            old_name='keyfeature',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='macbooks',
            old_name='keyfeature',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='keyfeature',
            new_name='description',
        ),
    ]
